# ---------------------------------------------------------------------------
# Certificate objects.
#
# NOTE ON for_each AND SENSITIVITY
#   Terraform refuses to use a sensitive collection in for_each, so the
#   iteration is driven by the plain, non-sensitive id LISTS and the sensitive
#   PEM material is looked up inside the resource body.
#
# NOTE ON PRIVATE KEYS IN S3
#   Writing a private key into S3 is exactly the discovery scenario being
#   tested. Every key here is a throwaway generated by this lab.
# ---------------------------------------------------------------------------

locals {
  store_ids           = toset(var.store_certificate_ids)
  store_openssl_ids   = toset(var.store_openssl_certificate_ids)
  staging_ids         = toset(var.staging_certificate_ids)
  staging_openssl_ids = toset(var.staging_openssl_certificate_ids)

  chain_ids = setintersection(
    toset(var.ca_signed_certificate_ids),
    setunion(local.store_ids, local.staging_ids),
  )
}

# --- Discovery targets: PEM / CRT / chain (phase1-cert-025) ---------------
resource "aws_s3_object" "store_certificate_pem" {
  for_each = local.store_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.certificate_prefix}/${each.key}/cert.pem"
  content                = var.generated_material[each.key].certificate_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, lookup(var.certificate_tags, each.key, {}), {
    Name                     = "${each.key}-cert.pem"
    CertificateStorageFormat = "PEM"
  })
}

resource "aws_s3_object" "store_certificate_crt" {
  for_each = local.store_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.certificate_prefix}/${each.key}/cert.crt"
  content                = var.generated_material[each.key].certificate_pem
  content_type           = "application/x-x509-ca-cert"
  server_side_encryption = "AES256"

  tags = merge(var.tags, lookup(var.certificate_tags, each.key, {}), {
    Name                     = "${each.key}-cert.crt"
    CertificateStorageFormat = "CRT"
  })
}

resource "aws_s3_object" "store_certificate_fullchain" {
  for_each = local.store_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.certificate_prefix}/${each.key}/fullchain.pem"
  content                = var.generated_material[each.key].fullchain_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, lookup(var.certificate_tags, each.key, {}), {
    Name                     = "${each.key}-fullchain.pem"
    CertificateStorageFormat = "PEM_CHAIN"
  })
}

resource "aws_s3_object" "store_certificate_chain" {
  for_each = setintersection(local.chain_ids, local.store_ids)

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.certificate_prefix}/${each.key}/chain.pem"
  content                = var.generated_material[each.key].chain_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, lookup(var.certificate_tags, each.key, {}), {
    Name                     = "${each.key}-chain.pem"
    CertificateStorageFormat = "PEM_CHAIN"
  })
}

resource "aws_s3_object" "store_private_key" {
  for_each = local.store_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.certificate_prefix}/${each.key}/cert.key"
  content                = var.generated_material[each.key].private_key_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, lookup(var.certificate_tags, each.key, {}), {
    Name                     = "${each.key}-cert.key"
    CertificateStorageFormat = "PRIVATE_KEY_PEM"
  })
}

# --- Discovery targets from the OpenSSL helper (phase1-cert-026) ----------
resource "aws_s3_object" "store_openssl_certificate" {
  for_each = local.store_openssl_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.certificate_prefix}/${each.key}/cert.crt"
  content                = var.openssl_material[each.key].certificate_pem
  content_type           = "application/x-x509-ca-cert"
  server_side_encryption = "AES256"

  tags = merge(var.tags, lookup(var.certificate_tags, each.key, {}), {
    Name                     = "${each.key}-cert.crt"
    CertificateStorageFormat = "CRT"
  })
}

# PKCS#12 / PFX keystore - the binary certificate container scenario.
resource "aws_s3_object" "store_pkcs12" {
  for_each = var.pkcs12_certificate_id == null ? toset([]) : toset([var.pkcs12_certificate_id])

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.certificate_prefix}/${each.key}/test.p12"
  content_base64         = var.pkcs12_base64
  content_type           = "application/x-pkcs12"
  server_side_encryption = "AES256"

  tags = merge(var.tags, lookup(var.certificate_tags, each.key, {}), {
    Name                     = "${each.key}-test.p12"
    CertificateStorageFormat = "PKCS12"
  })
}

resource "aws_s3_object" "store_pfx" {
  for_each = var.pkcs12_certificate_id == null ? toset([]) : toset([var.pkcs12_certificate_id])

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.certificate_prefix}/${each.key}/test.pfx"
  content_base64         = var.pkcs12_base64
  content_type           = "application/x-pkcs12"
  server_side_encryption = "AES256"

  tags = merge(var.tags, lookup(var.certificate_tags, each.key, {}), {
    Name                     = "${each.key}-test.pfx"
    CertificateStorageFormat = "PFX"
  })
}

# --- EC2 bootstrap staging (NOT primary discovery targets) ---------------
resource "aws_s3_object" "staging_certificate" {
  for_each = local.staging_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.ec2_staging_prefix}/${each.key}/cert.pem"
  content                = var.generated_material[each.key].certificate_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, { Name = "${each.key}-staging-cert.pem", StagingFor = "ec2" })
}

resource "aws_s3_object" "staging_fullchain" {
  for_each = local.staging_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.ec2_staging_prefix}/${each.key}/fullchain.pem"
  content                = var.generated_material[each.key].fullchain_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, { Name = "${each.key}-staging-fullchain.pem", StagingFor = "ec2" })
}

resource "aws_s3_object" "staging_private_key" {
  for_each = local.staging_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.ec2_staging_prefix}/${each.key}/cert.key"
  content                = var.generated_material[each.key].private_key_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, { Name = "${each.key}-staging-cert.key", StagingFor = "ec2" })
}

resource "aws_s3_object" "staging_openssl_certificate" {
  for_each = local.staging_openssl_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.ec2_staging_prefix}/${each.key}/cert.pem"
  content                = var.openssl_material[each.key].certificate_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, { Name = "${each.key}-staging-cert.pem", StagingFor = "ec2" })
}

resource "aws_s3_object" "staging_openssl_private_key" {
  for_each = local.staging_openssl_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.ec2_staging_prefix}/${each.key}/cert.key"
  content                = var.openssl_material[each.key].private_key_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, { Name = "${each.key}-staging-cert.key", StagingFor = "ec2" })
}

resource "aws_s3_object" "staging_openssl_chain" {
  for_each = local.staging_openssl_ids

  bucket                 = aws_s3_bucket.certificates.id
  key                    = "${var.ec2_staging_prefix}/${each.key}/chain.pem"
  content                = var.openssl_material[each.key].chain_pem
  content_type           = "application/x-pem-file"
  server_side_encryption = "AES256"

  tags = merge(var.tags, { Name = "${each.key}-staging-chain.pem", StagingFor = "ec2" })
}
