# ---------------------------------------------------------------------------
# phases/phase-1/secrets
#
# Two non-ACM certificate stores:
#
#   secrets_manager.tf   phase1-cert-021, phase1-cert-022
#   parameter_store.tf   phase1-cert-023, phase1-cert-024
#
# Secret / parameter names are deliberately PREDICTABLE so the discovery
# application can list a known prefix:
#
#   /certificate-test/phase1/cert-021
#   /certificate-test/phase1/cert-023/certificate
#
# All material is throwaway test material generated by this lab.
# ---------------------------------------------------------------------------

variable "name_prefix" {
  description = "Name prefix from modules/common."
  type        = string
}

variable "tags" {
  description = "Common tags."
  type        = map(string)
}

variable "certificate_tags" {
  description = "Per-scenario tag maps keyed by certificate id."
  type        = map(map(string))
}

variable "store_path_prefix" {
  description = "Shared path prefix for both Secrets Manager secrets and Parameter Store parameters."
  type        = string
  default     = "/certificate-test/phase1"

  validation {
    condition     = startswith(var.store_path_prefix, "/") && !endswith(var.store_path_prefix, "/")
    error_message = "store_path_prefix must start with / and must not end with /."
  }
}

variable "enable_secrets_manager" {
  description = "Create the Secrets Manager certificate scenarios. COST: 0.40 USD per secret per month."
  type        = bool
  default     = true
}

variable "enable_parameter_store" {
  description = "Create the SSM Parameter Store certificate scenarios. Standard-tier parameters are free."
  type        = bool
  default     = true
}

variable "secrets_recovery_window_days" {
  description = "Secrets Manager recovery window. 0 means immediate deletion on destroy, which is what you want for a disposable lab - otherwise the names stay reserved for up to 30 days and a re-apply fails."
  type        = number
  default     = 0

  validation {
    condition     = var.secrets_recovery_window_days == 0 || (var.secrets_recovery_window_days >= 7 && var.secrets_recovery_window_days <= 30)
    error_message = "secrets_recovery_window_days must be 0, or between 7 and 30."
  }
}

variable "secrets_manager_certificate_ids" {
  description = "Certificate ids stored in Secrets Manager, sourced from generated_material."
  type        = list(string)
  default     = []
}

variable "parameter_store_certificate_ids" {
  description = "Certificate ids stored in Parameter Store, sourced from generated_material."
  type        = list(string)
  default     = []
}

variable "parameter_store_openssl_certificate_ids" {
  description = "Certificate ids stored in Parameter Store, sourced from openssl_material (the EXPIRED scenario)."
  type        = list(string)
  default     = []
}

variable "generated_material" {
  description = "PEM material from the acm module. SENSITIVE."
  type = map(object({
    certificate_pem = string
    fullchain_pem   = string
    chain_pem       = string
    private_key_pem = string
    not_after       = string
    ca_signed       = bool
  }))
  sensitive = true
}

variable "openssl_material" {
  description = "PEM material from the OpenSSL helper. SENSITIVE."
  type = map(object({
    certificate_pem = string
    private_key_pem = string
    chain_pem       = string
  }))
  default   = {}
  sensitive = true
}

variable "certificate_domains" {
  description = "Certificate id to primary domain, used only to populate a non-sensitive description/tag."
  type        = map(string)
  default     = {}
}
